# VPC
vpc:
  name: swapnil
  cidr: "10.64.0.0/16"
  # azs:
  #   - us-east-1a
  #   - us-east-1c
  private_subnets:
    - "10.64.0.0/24"
    - "10.64.1.0/24"
  public_subnets:
    - "10.64.2.0/24"
    - "10.64.3.0/24"

common:
  security_group:
    ingress_with_cidr_blocks:
      - from_port: 8080
        to_port: 8090
        protocol: "tcp"
        description: "User-service ports"
        cidr_blocks: "0.0.0.0/0"
      - rule: "ssh-tcp"
        cidr_blocks: "0.0.0.0/0"
      - rule: "http-80-tcp"
        cidr_blocks: "0.0.0.0/0"
      - rule: "https-443-tcp"
        cidr_blocks: "0.0.0.0/0"
    egress_with_cidr_blocks:
      - from_port: 0
        to_port: 0
        protocol: "-1"
        description: "Allow all IPv4 outbound traffic"
        cidr_blocks: "0.0.0.0/0"


# EC2
ec2:
  ami_id: "ami-0ff8a91507f77f867"
  key:
    name: "swapnil-non-prod-account-dev"
    local_path: "~/.ssh/id_ed25519.pub"

